local Cmp = {
	CmpItemAbbrDeprecated = { fg = C.gray, style = "strikethrough" },
	CmpItemAbbrMatch = { fg = C.ui3_blue },
	CmpItemAbbrMatchFuzzy = { fg = C.ui3_blue },
	CmpItemKindFunction = { fg = C.yellow_orange },
	CmpItemKindMethod = { fg = C.yellow_orange },
	CmpItemKindConstructor = { fg = C.aurora_cyan },
	CmpItemKindClass = { fg = C.aurora_cyan },
	CmpItemKindEnum = { fg = C.ui_orange },
	CmpItemKindEvent = { fg = C.ui_purple },
	CmpItemKindInterface = { fg = C.light_blue },
	CmpItemKindStruct = { fg = C.light_blue },
	CmpItemKindVariable = { fg = C.light_gray },
	CmpItemKindField = { fg = C.light_gray },
	CmpItemKindProperty = { fg = C.yellow_orange },
	CmpItemKindEnumMember = { fg = C.light_blue },
	CmpItemKindConstant = { fg = C.vivid_blue },
	CmpItemKindKeyword = { fg = C.light_blue },
	CmpItemKindModule = { fg = C.purple },
	CmpItemKindValue = { fg = C.green },
	CmpItemKindUnit = { fg = C.fg },
	CmpItemKindText = { fg = C.light_green },
	CmpItemKindSnippet = { fg = C.context },
	CmpItemKindFile = { fg = C.fg },
	CmpItemKindFolder = { fg = C.folder_blue },
	CmpItemKindColor = { fg = C.fg },
	CmpItemKindReference = { fg = C.fg },
	CmpItemKindOperator = { fg = C.light_blue },
	CmpItemKindTypeParameter = { fg = C.fg },
}

return Cmp
