local highlights = {
	Normal = { fg = C.fg, bg = Config.transparent_background and "NONE" or C.bg },
	SignColumn = { bg = C.bg },
	MsgArea = { fg = C.fg, bg = Config.transparent_background and "NONE" or C.bg },
	ModeMsg = { fg = C.fg, bg = C.bg },
	MsgSeparator = { fg = C.fg, bg = C.bg },
	SpellBad = { fg = C.light_red, style = "underline" },
	SpellCap = { fg = C.yellow, style = "underline" },
	SpellLocal = { fg = C.green, style = "underline" },
	SpellRare = { fg = C.purple, style = "underline" },
	NormalNC = { fg = C.fg, bg = Config.transparent_background and "NONE" or C.bg },
	Pmenu = { fg = C.light_gray, bg = C.menu_gray },
	PmenuSel = { bg = C.ui2_blue },
	WildMenu = { fg = C.fg, bg = C.ui2_blue },
	CursorLineNr = { fg = C.light_gray, style = "bold" },
	Comment = { fg = C.gray, style = "italic" },
	Folded = { fg = C.folder_blue, bg = C.bg },
	FoldColumn = { fg = C.folder_blue, bg = C.bg },
	LineNr = { fg = C.gray },
	FloatBorder = { fg = C.gray, bg = C.menu_gray },
	Whitespace = { fg = C.bg },
	VertSplit = { fg = C.gray, bg = C.bg },
	CursorLine = { bg = C.line_bg },
	CursorColumn = { bg = C.line_bg },
	ColorColumn = { bg = C.gray },
	NormalFloat = { bg = C.menu_gray },
	Visual = { bg = C.ui_blue },
	VisualNOS = { bg = C.alt_bg },
	WarningMsg = { fg = C.error_red, bg = C.bg },
	DiffAdd = { fg = C.alt_bg, bg = C.sign_add },
	DiffChange = { fg = C.alt_bg, bg = C.sign_change, style = "underline" },
	DiffDelete = { fg = C.alt_bg, bg = C.sign_delete },
	QuickFixLine = { bg = C.ui2_blue },
	PmenuSbar = { bg = C.alt_bg },
	PmenuThumb = { bg = C.gray },
	MatchWord = { style = "underline" },
	MatchParen = { fg = C.hint_blue, bg = C.bg, style = "underline" },
	MatchWordCur = { style = "underline" },
	MatchParenCur = { style = "underline" },
	Cursor = { fg = C.cursor_fg, bg = C.cursor_bg },
	lCursor = { fg = C.cursor_fg, bg = C.cursor_bg },
	CursorIM = { fg = C.cursor_fg, bg = C.cursor_bg },
	TermCursor = { fg = C.cursor_fg, bg = C.cursor_bg },
	TermCursorNC = { fg = C.cursor_fg, bg = C.cursor_bg },
	Conceal = { fg = C.accent },
	Directory = { fg = C.vivid_blue },
	SpecialKey = { fg = C.vivid_blue },
	Title = { fg = C.cyan },
	ErrorMsg = { fg = C.error_red, bg = C.bg },
	Search = { fg = C.light_gray, bg = C.search_blue },
	IncSearch = { fg = C.search_orange, bg = C.light_gray },
	Substitute = { fg = C.light_gray, bg = C.search_orange },
	MoreMsg = { fg = C.orange },
	Question = { fg = C.orange },
	EndOfBuffer = { fg = C.bg },
	NonText = { fg = C.bg },
	Variable = { fg = C.light_gray },
	String = { fg = C.orange },
	Character = { fg = C.orange },
	Constant = { fg = C.vivid_blue },
	Number = { fg = C.green },
	Boolean = { fg = C.green },
	Float = { fg = C.cyan },
	FloatTitle = { fg = C.comp_blue },
	Identifier = { fg = C.search_blue },
	Function = { fg = C.yellow_orange },
	Operator = { fg = C.comp_blue },
	Type = { fg = C.green },
	StorageClass = { fg = C.vivid_blue },
	Structure = { fg = C.yellow },
	Typedef = { fg = C.yellow },
	Keyword = { fg = C.light_blue },
	Statement = { fg = C.purple },
	Conditional = { fg = C.blue },
	Repeat = { fg = C.purple },
	Label = { fg = C.light_gray },
	Exception = { fg = C.purple },
	Include = { fg = C.purple },
	PreProc = { fg = C.yellow },
	Define = { fg = C.purple },
	Macro = { fg = C.purple },
	PreCondit = { fg = C.vivid_blue },
	Special = { fg = C.orange },
	SpecialChar = { fg = C.white },
	Tag = { fg = C.vivid_blue },
	Debug = { fg = C.red },
	Delimiter = { fg = C.comp_blue },
	SpecialComment = { fg = C.context, style = "italic" },
	Underlined = { style = "underline" },
	Bold = { style = "bold" },
	Italic = { style = "italic" },
	Ignore = { fg = C.cyan, bg = C.bg },
	Todo = { fg = C.light_red, bg = C.bg },
	Error = { fg = C.error_red, bg = C.bg },
	TabLine = { fg = C.light_gray, bg = C.alt_bg },
	TabLineSel = { fg = C.white, bg = C.alt_bg },
	TabLineFill = { fg = C.alt_bg, bg = C.alt_bg },
  WinBar = {fg = C.fg},
  WinBarNC = {fg = C.fg},
}

return highlights
