local LSP = {
		LspDiagnosticsDefaultError = {fg = C.error_red, },
		LspDiagnosticsDefaultWarning = {fg = C.warning_orange, },
		LspDiagnosticsDefaultInformation = {fg = C.info_yellow, },
		LspDiagnosticsDefaultInfo = {fg = C.info_yellow, },
		LspDiagnosticsDefaultHint = {fg = C.fg, },
		LspDiagnosticsVirtualTextError = {fg = C.error_red, },
		LspDiagnosticsVirtualTextWarning = {fg = C.warning_orange, },
		LspDiagnosticsVirtualTextInformation = {fg = C.info_yellow, },
		LspDiagnosticsVirtualTextInfo = {fg = C.info_yellow, },
		LspDiagnosticsVirtualTextHint = {fg = C.fg, },
		LspDiagnosticsFloatingError = {fg = C.error_red, },
		LspDiagnosticsFloatingWarning = {fg = C.warning_orange, },
		LspDiagnosticsFloatingInformation = {fg = C.info_yellow, },
		LspDiagnosticsFloatingInfo = {fg = C.info_yellow, },
		LspDiagnosticsFloatingHint = {fg = C.fg, },
		DiagnosticSignError = {fg = C.error_red, },
		DiagnosticSignWarning = {fg = C.warning_orange, },
		DiagnosticSignInformation = {fg = C.info_yellow, },
		DiagnosticSignInfo = {fg = C.info_yellow, },
		DiagnosticSignHint = {fg = C.fg, },
		LspDiagnosticsSignError = {fg = C.error_red, },
		LspDiagnosticsSignWarning = {fg = C.warning_orange, },
		LspDiagnosticsSignInformation = {fg = C.info_yellow, },
		LspDiagnosticsSignInfo = {fg = C.info_yellow, },
		LspDiagnosticsSignHint = {fg = C.fg, },
		LspDiagnosticsError = {fg = C.error_red, },
		LspDiagnosticsWarning = {fg = C.warning_orange, },
		LspDiagnosticsInformation = {fg = C.fg, },
		LspDiagnosticsInfo = {fg = C.fg, },
		LspDiagnosticsHint = {fg = C.info_yellow, },
		LspDiagnosticsUnderlineError = {style = "underline", },
		LspDiagnosticsUnderlineWarning = {style = "underline", },
		LspDiagnosticsUnderlineInformation = {style = "underline", },
		LspDiagnosticsUnderlineInfo = {style = "underline", },
		LspDiagnosticsUnderlineHint = {style = "underline", },
		LspReferenceRead = {bg = "#464c55", },
		LspReferenceText = {bg = "#464c55", },
		LspReferenceWrite = {bg = "#464c55", },
}

return LSP
